### ISSUE TITLE
[New Build System] Moving workspaces to library files

### ISSUE THREAD

**Issue by SergioRibera** [heavy-duty/znap#108]
Currently the file structure looks like this

```
proyect/
  Cargo.toml
  znap.toml
  collections/
    send-donation/
      Cargo.toml
      src/lib.rs
    other/
      Cargo.toml
      src/lib.rs
```

The new proposal is intended to look like this

```
proyect/
  Cargo.toml
  znap.toml
  collections/
    send_donation.rs
    other.rs
```

This is not only possible but reduces many possible problems, this is possible but requires modifying the toml, so it would be nice to implement these changes to the migration command, by the toml charge, it can be like this and manage certain changes based on features

```toml
# changes on Cargo.toml

[[bin]]
name = "collection_name"
path = "collections/collection_name.rs"

[[bin]]
name = "other_collection_name"
path = "collections/other_collection_name.rs"
```

The macro structure and code are not affected, but the [build commands](https://github.com/heavy-duty/znap/blob/53c399fb4d4cc9e54eac233e7c07f5a654447b5b/znap-cli/src/utils/mod.rs#L278-L293) are probably affected by obliterating the [`--bin collection_name` arguments](https://doc.rust-lang.org/cargo/commands/cargo-build.html#target-selection)

> [!IMPORTANT]
> All changes should PR to the [runtime](https://github.com/heavy-duty/znap/tree/runtime) branch
