### ISSUE TITLE
The Identity breaks the API in Shuttle and during Tests in the Github Actions runtime

### ISSUE THREAD

**Issue by danmt** [heavy-duty/znap#83]
Action Identities let Action Providers have verifiable on-chain transactions. The mechanics behind it are pretty simple, we have a secret key used to sign a unique message attached to each transaction returned by the API, this is then used to verify the authentication of an Action.

The way this works atm involves an `identity` property in the `Znap.toml` file pointing to the same path where Solana stores the default Keypair in your OS `~/.config/solana/id.json`. This works fine locally as long as you have such file and you can serve the API in your server and by having a keypair that path you can assure it all works well.

The problem comes when we try to serve the API in a run-time outside our direct control. For example, the Shuttle runtime doesn't have such path available, the keypair should be store somewhere else and should be accessible within the run-time serving the API. The same happens with the GitHub Action run-time.

There are multiple ways to solve this, we want to avoid changing Znap API as much as possible. Being able to configure this in the Znap.toml without changing the logic of the framework would be a great solution. For Shuttle and Github runtime, we need a way to "upload" or "set up" a keypair. For tests it might make sense to generate it on-demand, for Shuttle in the other hand might be better to have one fixed.

Something like this in the `Znap.toml` might work:

```toml
[local]
identity = "~/.config/solana/id.json"

[deploy]
identity = "<another path that works for your specific deployment>"

[ci]
identity = "<another path that works for the ci environment>"
```
